# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'anaekran.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 0, 740, 61))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(5, 120, 790, 431))
        self.tableWidget.setMaximumSize(QtCore.QSize(790, 431))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(7)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        self.tableWidget.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(120)
        self.tableWidget.horizontalHeader().setStretchLastSection(False)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(40, 50, 381, 61))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.doluluk_orani = QtWidgets.QLabel(self.centralwidget)
        self.doluluk_orani.setGeometry(QtCore.QRect(280, 50, 381, 61))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.doluluk_orani.setFont(font)
        self.doluluk_orani.setAlignment(QtCore.Qt.AlignCenter)
        self.doluluk_orani.setObjectName("doluluk_orani")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        self.menu_yonetim = QtWidgets.QMenu(self.menubar)
        self.menu_yonetim.setObjectName("menu_yonetim")
        self.menu_uyelik_islemleri = QtWidgets.QMenu(self.menubar)
        self.menu_uyelik_islemleri.setObjectName("menu_uyelik_islemleri")
        self.menu_egitmen_islemleri = QtWidgets.QMenu(self.menubar)
        self.menu_egitmen_islemleri.setObjectName("menu_egitmen_islemleri")
        self.menuTarife_lemleri = QtWidgets.QMenu(self.menubar)
        self.menuTarife_lemleri.setObjectName("menuTarife_lemleri")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action_yonetici_ekle = QtWidgets.QAction(MainWindow)
        self.action_yonetici_ekle.setObjectName("action_yonetici_ekle")
        self.action_yonetici_guncelle = QtWidgets.QAction(MainWindow)
        self.action_yonetici_guncelle.setObjectName("action_yonetici_guncelle")
        self.action_cikis = QtWidgets.QAction(MainWindow)
        self.action_cikis.setObjectName("action_cikis")
        self.action_uye_ekle = QtWidgets.QAction(MainWindow)
        self.action_uye_ekle.setObjectName("action_uye_ekle")
        self.action_uye_guncelle_sil = QtWidgets.QAction(MainWindow)
        self.action_uye_guncelle_sil.setObjectName("action_uye_guncelle_sil")
        self.action_egitmen_ekle = QtWidgets.QAction(MainWindow)
        self.action_egitmen_ekle.setObjectName("action_egitmen_ekle")
        self.action_egitmen_guncelle_sil = QtWidgets.QAction(MainWindow)
        self.action_egitmen_guncelle_sil.setObjectName("action_egitmen_guncelle_sil")
        self.action_giris = QtWidgets.QAction(MainWindow)
        self.action_giris.setObjectName("action_giris")
        self.action_arac_girisi = QtWidgets.QAction(MainWindow)
        self.action_arac_girisi.setObjectName("action_arac_girisi")
        self.action_arac_cikisi = QtWidgets.QAction(MainWindow)
        self.action_arac_cikisi.setObjectName("action_arac_cikisi")
        self.action_abone_Ekle = QtWidgets.QAction(MainWindow)
        self.action_abone_Ekle.setObjectName("action_abone_Ekle")
        self.action_abone_Sil = QtWidgets.QAction(MainWindow)
        self.action_abone_Sil.setObjectName("action_abone_Sil")
        self.action_birim_zaman_tutari = QtWidgets.QAction(MainWindow)
        self.action_birim_zaman_tutari.setObjectName("action_birim_zaman_tutari")
        self.action_zaman_katsayilari = QtWidgets.QAction(MainWindow)
        self.action_zaman_katsayilari.setObjectName("action_zaman_katsayilari")
        self.action_arac_katsayilari = QtWidgets.QAction(MainWindow)
        self.action_arac_katsayilari.setObjectName("action_arac_katsayilari")
        self.action_eski_parklar = QtWidgets.QAction(MainWindow)
        self.action_eski_parklar.setObjectName("action_eski_parklar")
        self.menu_yonetim.addAction(self.action_giris)
        self.menu_yonetim.addAction(self.action_yonetici_ekle)
        self.menu_yonetim.addAction(self.action_yonetici_guncelle)
        self.menu_yonetim.addAction(self.action_cikis)
        self.menu_uyelik_islemleri.addAction(self.action_arac_girisi)
        self.menu_uyelik_islemleri.addAction(self.action_arac_cikisi)
        self.menu_uyelik_islemleri.addAction(self.action_eski_parklar)
        self.menu_egitmen_islemleri.addAction(self.action_abone_Ekle)
        self.menu_egitmen_islemleri.addAction(self.action_abone_Sil)
        self.menuTarife_lemleri.addAction(self.action_birim_zaman_tutari)
        self.menuTarife_lemleri.addAction(self.action_zaman_katsayilari)
        self.menuTarife_lemleri.addAction(self.action_arac_katsayilari)
        self.menubar.addAction(self.menu_yonetim.menuAction())
        self.menubar.addAction(self.menu_uyelik_islemleri.menuAction())
        self.menubar.addAction(self.menu_egitmen_islemleri.menuAction())
        self.menubar.addAction(self.menuTarife_lemleri.menuAction())

        self.retranslateUi(MainWindow)
        self.action_cikis.triggered.connect(MainWindow.close)
        self.action_giris.triggered.connect(MainWindow.show)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Otopark Otomasyonu"))
        self.label.setText(_translate("MainWindow", "Otopark Otomasyonuna Hoş Geldiniz"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Araç Plakası"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Giriş Zamanı"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Abonelik Durumu"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Araç Tipi"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Ücret Hesapla"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Tutar"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Çıkış Yap"))
        self.label_2.setText(_translate("MainWindow", "Doluluk Oranı :"))
        self.doluluk_orani.setText(_translate("MainWindow", "Doluluk Oranı"))
        self.menu_yonetim.setTitle(_translate("MainWindow", "Yönetim"))
        self.menu_uyelik_islemleri.setTitle(_translate("MainWindow", "Park İşlemleri"))
        self.menu_egitmen_islemleri.setTitle(_translate("MainWindow", "Abone İşlemleri"))
        self.menuTarife_lemleri.setTitle(_translate("MainWindow", "Tarife İşlemleri"))
        self.action_yonetici_ekle.setText(_translate("MainWindow", "Yönetici Ekle"))
        self.action_yonetici_guncelle.setText(_translate("MainWindow", "Yönetici Güncelle - Sil"))
        self.action_cikis.setText(_translate("MainWindow", "Çıkış"))
        self.action_uye_ekle.setText(_translate("MainWindow", "Üye Ekle"))
        self.action_uye_guncelle_sil.setText(_translate("MainWindow", "Üye Güncelle / Sil"))
        self.action_egitmen_ekle.setText(_translate("MainWindow", "Eğitmen Ekle"))
        self.action_egitmen_guncelle_sil.setText(_translate("MainWindow", "Eğitmen Güncelle / Sil"))
        self.action_giris.setText(_translate("MainWindow", "Giriş"))
        self.action_arac_girisi.setText(_translate("MainWindow", "Araç Girişi"))
        self.action_arac_cikisi.setText(_translate("MainWindow", "Araç Çıkışı"))
        self.action_abone_Ekle.setText(_translate("MainWindow", "Abone Ekle"))
        self.action_abone_Sil.setText(_translate("MainWindow", "Abone Sil"))
        self.action_birim_zaman_tutari.setText(_translate("MainWindow", "Birim Zaman Tutarı"))
        self.action_zaman_katsayilari.setText(_translate("MainWindow", "Zamansal Kat Sayıları"))
        self.action_arac_katsayilari.setText(_translate("MainWindow", "Araç Katsayıları"))
        self.action_eski_parklar.setText(_translate("MainWindow", "Eski Parklar"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

