# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'uye_ekleme.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(800, 600)
        self.formLayoutWidget = QtWidgets.QWidget(Form)
        self.formLayoutWidget.setGeometry(QtCore.QRect(130, 110, 531, 401))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.yNeticiAdLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.yNeticiAdLabel.setObjectName("yNeticiAdLabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.yNeticiAdLabel)
        self.uye_adi_soyadi = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.uye_adi_soyadi.setObjectName("uye_adi_soyadi")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.uye_adi_soyadi)
        self.yNeticiTCNoLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.yNeticiTCNoLabel.setObjectName("yNeticiTCNoLabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.yNeticiTCNoLabel)
        self.uye_tc = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.uye_tc.setObjectName("uye_tc")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.uye_tc)
        self.yNeticiIfreLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.yNeticiIfreLabel.setObjectName("yNeticiIfreLabel")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.yNeticiIfreLabel)
        self.uye_sifre = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.uye_sifre.setObjectName("uye_sifre")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.uye_sifre)
        self.yNeticiDurumuLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.yNeticiDurumuLabel.setObjectName("yNeticiDurumuLabel")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.yNeticiDurumuLabel)
        self.uye_durum = QtWidgets.QComboBox(self.formLayoutWidget)
        self.uye_durum.setObjectName("uye_durum")
        self.uye_durum.addItem("")
        self.uye_durum.addItem("")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.uye_durum)
        self.yelikBitiTarihiLabel_2 = QtWidgets.QLabel(self.formLayoutWidget)
        self.yelikBitiTarihiLabel_2.setObjectName("yelikBitiTarihiLabel_2")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.yelikBitiTarihiLabel_2)
        self.uyelik_tarihi = QtWidgets.QDateEdit(self.formLayoutWidget)
        self.uyelik_tarihi.setDateTime(QtCore.QDateTime(QtCore.QDate(2000, 1, 5), QtCore.QTime(0, 0, 0)))
        self.uyelik_tarihi.setCalendarPopup(True)
        self.uyelik_tarihi.setObjectName("uyelik_tarihi")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.uyelik_tarihi)
        self.uye_ekle_btn = QtWidgets.QPushButton(self.formLayoutWidget)
        self.uye_ekle_btn.setObjectName("uye_ekle_btn")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.uye_ekle_btn)
        self.yeTelefonLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.yeTelefonLabel.setObjectName("yeTelefonLabel")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.yeTelefonLabel)
        self.uye_tel = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.uye_tel.setObjectName("uye_tel")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.uye_tel)
        self.yeAdresLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.yeAdresLabel.setObjectName("yeAdresLabel")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.yeAdresLabel)
        self.uye_adres = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.uye_adres.setObjectName("uye_adres")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.uye_adres)
        self.yeNotuLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.yeNotuLabel.setObjectName("yeNotuLabel")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.yeNotuLabel)
        self.uye_notu = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.uye_notu.setObjectName("uye_notu")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.uye_notu)
        self.eItmenLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.eItmenLabel.setObjectName("eItmenLabel")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.eItmenLabel)
        self.egitmen = QtWidgets.QComboBox(self.formLayoutWidget)
        self.egitmen.setObjectName("egitmen")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.egitmen)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(30, 50, 740, 61))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Üye Ekleme Ekranı"))
        self.yNeticiAdLabel.setText(_translate("Form", "Üye Adı Soyadı"))
        self.yNeticiTCNoLabel.setText(_translate("Form", "Üye T.C. No "))
        self.yNeticiIfreLabel.setText(_translate("Form", "Üye Şifre"))
        self.yNeticiDurumuLabel.setText(_translate("Form", "Üye Durumu"))
        self.uye_durum.setItemText(0, _translate("Form", "Aktif"))
        self.uye_durum.setItemText(1, _translate("Form", "Pasif"))
        self.yelikBitiTarihiLabel_2.setText(_translate("Form", "Üyelik Bitiş Tarihi"))
        self.uye_ekle_btn.setText(_translate("Form", "Yeni Üye Ekle"))
        self.yeTelefonLabel.setText(_translate("Form", "Üye Telefon"))
        self.yeAdresLabel.setText(_translate("Form", "Üye Adres"))
        self.yeNotuLabel.setText(_translate("Form", "Üye Notu"))
        self.eItmenLabel.setText(_translate("Form", "Eğitmen"))
        self.label.setText(_translate("Form", "Yeni Üye Ekleme Formu"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

